# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compute_closest_distance_helper <- function(a, b, c, d, sc, nthread) {
    .Call(`_CausalGPS_compute_closest_distance_helper`, a, b, c, d, sc, nthread)
}

compute_closest_wgps_helper <- function(a, b, cd, sc, nthread) {
    .Call(`_CausalGPS_compute_closest_wgps_helper`, a, b, cd, sc, nthread)
}

